package com.edu.unlu.generala.vista;

public enum EstadoVistaConsola {
    MENU_PRINCIPAL,
    MENU_JUGADOR_DADOS,
    MENU_JUGADOR_APUESTAS,
    AGREGAR_JUGADOR,
    DEPOSITAR,
    INGRESA_INDICES_RETIRO,
    ALTA_APUESTA,
    RONDA_APUESTAS_INICIAL,
    TIRAR_DADOS,
    RONDA_APUESTAS_FINAL,
    MANTENER_DADOS

}
